# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Azure Function - Registerapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Publish Azure Function
        run: dotnet publish -c Release -o ./publish
        working-directory: backend/RegistationApplication

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_914E34D8F5854FB68A908403E684AE17 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87E8328FBBCF4DD4A14AED1504752685 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3BDC8B159BD04687AC52BE0521B17FE7 }}

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: 'Registerapp'
          slot-name: 'Production'
          package: 'backend/RegistationApplication/publish'
          